// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Check VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom fetch wrapper that applies timeouts to Supabase calls.
// Auth/token-refresh endpoints get 60 s — on Indian mobile networks the refresh
// can take several seconds, and killing it silently breaks subsequent mutations.
// All other data calls get 20 s.
const fetchWithTimeout: typeof fetch = (input, init) => {
  const url = typeof input === "string" ? input : input instanceof Request ? input.url : "";
  const isAuthRequest = url.includes("/auth/");
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), isAuthRequest ? 60_000 : 20_000);

  // Combine Supabase's own signal (if any) with our timeout signal so both work.
  let signal: AbortSignal = controller.signal;
  if (init?.signal) {
    try {
      // AbortSignal.any is available in Chrome 116+, Firefox 115+, Safari 17.4+
      signal = (AbortSignal as any).any([controller.signal, init.signal]);
    } catch {
      // Fallback: use our controller only (still provides the timeout)
      signal = controller.signal;
    }
  }

  return fetch(input, { ...init, signal }).finally(() => clearTimeout(timer));
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: fetchWithTimeout,
  },
});